// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_timeLBL;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Spinner2;
extern lv_obj_t *ui_Chart2;
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_numberLBL;
extern lv_obj_t *ui_Arc2;
extern lv_obj_t *ui_batLBL;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_Panel13;
extern lv_obj_t *ui_Panel14;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_fpdLBL;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_mhzLBL;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_secLBL;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_166767699);   // assets/Pictogrammers-Material-Car-light-high.24.png
LV_IMG_DECLARE( ui_img_125158209);   // assets/Custom-Icon-Design-Mono-General-4-Power.24.png
LV_IMG_DECLARE( ui_img_682691754);   // assets/Custom-Icon-Design-Mono-General-4-Power.32.png
LV_IMG_DECLARE( ui_img_1292625414);   // assets/Iconsmind-Outline-Temperature.16.png
LV_IMG_DECLARE( ui_img_85708210);   // assets/Pictogrammers-Material-Car-light-high.32.png
LV_IMG_DECLARE( ui_img_1932778759);   // assets/Pictogrammers-Material-Car-light-high.48.png
LV_IMG_DECLARE( ui_img_117657630);   // assets/Pictogrammers-Material-Car-light-high.72.png


LV_FONT_DECLARE( ui_font_big);
LV_FONT_DECLARE( ui_font_numbers);
LV_FONT_DECLARE( ui_font_small);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
