// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_timeLBL;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Spinner2;
lv_obj_t *ui_Chart2;
lv_obj_t *ui_Arc1;
lv_obj_t *ui_numberLBL;
lv_obj_t *ui_Arc2;
lv_obj_t *ui_batLBL;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Button2;
lv_obj_t *ui_Panel9;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Panel10;
lv_obj_t *ui_Panel11;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Panel8;
lv_obj_t *ui_Panel12;
lv_obj_t *ui_Panel13;
lv_obj_t *ui_Panel14;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Label15;
lv_obj_t *ui_fpdLBL;
lv_obj_t *ui_Label17;
lv_obj_t *ui_mhzLBL;
lv_obj_t *ui_Label18;
lv_obj_t *ui_secLBL;
lv_obj_t *ui_Panel7;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_73290616[2] = {&ui_img_125158209, &ui_img_682691754};
const lv_img_dsc_t *ui_imgset_1686079066[1] = {&ui_img_1292625414};
const lv_img_dsc_t *ui_imgset_2006143904[4] = {&ui_img_166767699, &ui_img_85708210, &ui_img_1932778759, &ui_img_117657630};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
